// Arabic text for the app, keyed by the English text used in the code.
// Anything missing here falls back to English.
export const AR: Record<string, string> = {
  // Tabs
  Chat: "الشات",
  Events: "المواعيد",
  Lists: "اللوائح",
  Online: "مين هون",
  Family: "العيلة",

  // Login
  "Welcome to": "أهلا بـ",
  "Your family, all in one place. No phone number needed.": "كل العيلة بمكان واحد، وبلا رقم تلفون.",
  "Your name": "اسمك",
  "Family code": "كود العيلة",
  "Joining…": "عم نفوت…",
  "Join my family": "فوت عالعيلة",
  "Family admin? Sign in here": "إنت أدمن العيلة؟ فوت من هون",
  "Admin sign in": "دخول الأدمن",
  "New admin": "أدمن جديد",
  "Password (6+ characters)": "كلمة السر (٦ حروف أو أكتر)",
  "Sign in": "دخول",
  "Create admin account": "اعمل حساب أدمن",
  "← Join with a family code instead": "→ فوت بكود العيلة",
  "Joining with a code is not switched on yet. Ask the family admin.": "الدخول بالكود مش مشغّل بعد. اسأل أدمن العيلة.",
  "That code is not right. Check it with the admin.": "الكود مش صح. تأكّد منو مع الأدمن.",
  "Check your email and tap the link to finish signing up.": "شوف الإيميل وكبس عالرابط لتكمّل التسجيل.",
  "Wrong email or password.": "الإيميل أو كلمة السر غلط.",

  // Home
  "Sign out": "طلوع",
  "Your families": "عيلاتك",
  "Loading…": "عم يحمّل…",
  "You're not in a family yet. Create one or join with a code.": "لسّا مش بأي عيلة. اعمل عيلة أو فوت بكود.",
  Code: "الكود",
  "Join a family": "فوت على عيلة",
  "Invite code, e.g. 4F9A2C": "كود الدعوة، مثلاً 4F9A2C",
  Join: "فوت",
  "Start a new family": "اعمل عيلة جديدة",
  "You'll be the admin and get the invite code.": "إنت بتصير الأدمن وبيكون معك كود الدعوة.",
  "Family name, e.g. Beit Jeddo": "اسم العيلة، مثلاً بيت جدّو",
  Create: "اعمل",

  // Family page
  Back: "رجوع",
  "Back home": "رجوع للبداية",
  "This family doesn't exist or you're not a member.": "هالعيلة مش موجودة أو إنت مش منها.",
  "{n} online": "{n} أونلاين",
  Someone: "حدا",
  "{name} is here · {time}": "{name} فات · {time}",

  // Chat
  "No messages yet. Say marhaba!": "ما في رسائل بعد. قول مرحبا!",
  "Write a message…": "اكتب رسالة…",
  Send: "بعات",
  Attach: "زيد",
  Photo: "صورة",
  Poll: "تصويت",
  "Voice message": "رسالة صوتية",
  "Record a voice message": "سجّل رسالة صوتية",
  "Recording…": "عم يسجّل…",
  "DinKin needs the microphone to record. Allow it in your phone settings.": "DinKin بدّو الميكروفون ليسجّل. سمحلو من إعدادات التلفون.",
  "Add a caption or tap send.": "اكتب شي تحت الصورة أو كبس بعات.",
  "Remove photo": "شيل الصورة",
  "Close photo": "سكّر الصورة",
  "Former member": "عضو قديم",
  "Delete this message?": "بدك تمحي هالرسالة؟",
  "Message deleted": "الرسالة انمحت",
  Reply: "ردّ",
  "Replying to {name}": "عم تردّ على {name}",
  Copy: "نسخ",
  Copied: "انتسخ",
  Delete: "محي",
  Cancel: "إلغاء",
  "Seen by everyone": "الكل شافها",
  "Seen by {names}": "شافها {names}",
  "{name} is typing…": "{name} عم يكتب…",
  "{names} are typing…": "{names} عم يكتبوا…",
  Today: "اليوم",
  Yesterday: "مبارح",
  "Today is {name}'s birthday!": "اليوم عيد ميلاد {name}!",
  "Happy birthday, {name}! 🎉": "عيد ميلاد سعيد يا {name}! 🎉",

  // Polls
  "New poll": "تصويت جديد",
  "Question, e.g. Where shall we eat?": "السؤال، مثلاً وين منتغدّى؟",
  "Option {n}": "خيار {n}",
  "Add option": "زيد خيار",
  "Send poll": "بعات التصويت",
  Remove: "شيل",
  "1 vote": "صوت واحد",
  "{n} votes": "{n} أصوات",

  // Events
  "New event": "موعد جديد",
  "Nothing on this day.": "ما في شي بهاليوم.",
  "Coming up": "جايين",
  "Nothing planned yet. Tap a day, then New event.": "ما في مواعيد بعد. كبس على يوم، وبعدين موعد جديد.",
  "Delete this event?": "بدك تمحي هالموعد؟",
  "Delete event": "محي الموعد",
  "Previous month": "الشهر اللي قبل",
  "Next month": "الشهر الجايي",
  "Go to today": "روح لليوم",
  "Added by {name}": "زادو {name}",
  someone: "حدا",
  "What? e.g. Teta's birthday dinner": "شو؟ مثلاً عشا عيد ميلاد تيتا",
  "Where? (optional)": "وين؟ (إذا بدك)",
  "Notes (optional)": "ملاحظات (إذا بدك)",
  "Save event": "احفظ الموعد",
  "No reminder": "بلا تذكير",
  "At the time": "بوقتو",
  "15 minutes before": "قبل ربع ساعة",
  "30 minutes before": "قبل نص ساعة",
  "1 hour before": "قبل ساعة",
  "3 hours before": "قبل ٣ ساعات",
  "1 day before": "قبل بيوم",
  "{n} minutes before": "قبل {n} دقيقة",
  "Remind everyone: {when}": "ذكّر الكل: {when}",
  "{name}'s birthday": "عيد ميلاد {name}",

  // Lists
  "Add item, e.g. Khebez": "زيد غرض، مثلاً خبز",
  Qty: "كمية",
  Add: "زيد",
  "To get ({n})": "لازم نجيب ({n})",
  "The list is empty. Yalla, add something!": "اللائحة فاضية. يلّا زيد شي!",
  "You will get it": "إنت رح تجيبو",
  "{name} will get it": "{name} رح يجيبو",
  Unclaim: "ما رح جيبو",
  "I'll get it": "أنا بجيبو",
  "Done ({n})": "خلصوا ({n})",
  "Clear done": "امحي اللي خلصوا",
  "Mark {item} not done": "رجّع {item} لسّا",

  // Online tab
  "In the chat": "بالشات",
  "Looking at events": "عم يتطلّع عالمواعيد",
  "Looking at lists": "عم يتطلّع عاللوائح",
  "Looking at who's online": "عم يشوف مين هون",
  "In family settings": "بإعدادات العيلة",
  "Online now": "أونلاين هلّق",
  you: "إنت",
  Since: "من",
  "Just arrived": "هلّق وصلوا",
  "{name} opened DinKin": "{name} فتح DinKin",
  Offline: "مش أونلاين",
  "Not seen yet": "ما بيّن بعد",
  "Last seen today at {time}": "آخر مرة اليوم الساعة {time}",
  "Last seen yesterday at {time}": "آخر مرة مبارح الساعة {time}",
  "Last seen {day} at {time}": "آخر مرة {day} الساعة {time}",

  // Family tab
  "Change family photo": "غيّر صورة العيلة",
  "Add a family photo": "حط صورة للعيلة",
  "Only you can see this code": "إنت بس بتشوف هالكود",
  "Invite code": "كود الدعوة",
  "Make a new code": "اعمل كود جديد",
  "Make a new code? The old code will stop working.": "بدك كود جديد؟ القديم بيوقف يشتغل.",
  "Want to add someone? Ask the family admin for the invite code.": "بدك تزيد حدا؟ اطلب كود الدعوة من أدمن العيلة.",
  "Run the latest database update (supabase/migrations) to show the code.": "شغّل آخر تحديث لقاعدة البيانات ليبيّن الكود.",
  'Join our family "{family}" on DinKin\n1. Open {link}\n2. Write your name and the code: {code}':
    'تعا فوت على عيلتنا "{family}" على DinKin\n١. افتح {link}\n٢. اكتب اسمك والكود: {code}',
  Members: "الأعضاء",
  Admin: "أدمن",
  "Last seen {when}": "آخر مرة {when}",
  "just now": "هلّق",
  "{n} min ago": "من {n} دقيقة",
  "{n} h ago": "من {n} ساعة",
  "Joined {date}": "فات {date}",
  "Make admin": "خلّيه أدمن",
  "Make {name} an admin? They will see the invite code and can remove members.": "بدك تخلّي {name} أدمن؟ رح يشوف كود الدعوة ويقدر يشيل أعضاء.",
  "Remove {name} from {family}?": "بدك تشيل {name} من {family}؟",
  "Your profile": "حسابك",
  "Change photo": "غيّر الصورة",
  "Add a photo": "حط صورة",
  "Uploading…": "عم يرفع…",
  "Your family will see it next to your name.": "العيلة بتشوفها حد اسمك.",
  "Could not change the photo.": "ما زبط نغيّر الصورة.",
  Save: "احفظ",
  Saved: "انحفظ",
  Birthday: "عيد الميلاد",
  Day: "اليوم",
  Month: "الشهر",
  "The family gets a reminder every year.": "العيلة بيوصلها تذكير كل سنة.",
  "Run database update 6 first.": "شغّل تحديث قاعدة البيانات رقم ٦ أول.",
  Password: "كلمة السر",
  "New password": "كلمة سر جديدة",
  "Password saved.": "كلمة السر انحفظت.",
  "Leave family": "اطلع من العيلة",
  "Leave {family}?": "بدك تطلع من {family}؟",
  "Sign out? To come back you will need the family code again.": "بدك تطلع؟ لترجع رح تحتاج كود العيلة مرة تانية.",
  Language: "اللغة",

  // Notifications
  "Get notified when family writes": "خلّي يوصلك إشعار لما العيلة تكتب",
  "Turning on…": "عم يشغّل…",
  "Turn on notifications": "شغّل الإشعارات",
  Hide: "خبّي",
  Notifications: "الإشعارات",
  "On for this device. You'll hear about new messages and events.": "شغّالة على هالتلفون. رح يوصلك خبر بالرسائل والمواعيد الجديدة.",
  "Turn off": "طفّي",
  "Turn on": "شغّل",
  "Get a notification when someone writes.": "خلّي يوصلك إشعار لما حدا يكتب.",
  "On iPhone: tap Share, then Add to Home Screen. Open DinKin from your home screen and turn notifications on there.":
    "عالآيفون: كبس مشاركة، وبعدين Add to Home Screen. افتح DinKin من الشاشة الرئيسية وشغّل الإشعارات من هونيك.",
  "Notifications are blocked. Allow them for DinKin in your phone or browser settings.": "الإشعارات مسكّرة. سمحلها لـ DinKin من إعدادات التلفون أو المتصفّح.",
  "This browser can't show notifications.": "هالمتصفّح ما بيقدر يبيّن إشعارات.",

  // Chat background
  "Chat background": "خلفية الشات",
  "Only you see it, on this phone.": "إنت بس بتشوفها، على هالتلفون.",
  "Choose a photo": "اختار صورة",
  Plain: "عادي",
  Cream: "كريمي",
  Rose: "وردي",
  Sunset: "غروب",
  Lavender: "خزامى",
  Wine: "خمري",
  Dots: "نقط",

  // Photo editor
  Undo: "رجوع",
  Rotate: "تدوير",
  Done: "تمام",
  "Opening photo…": "عم يفتح الصورة…",
  "Drag the square to choose the part to keep.": "حرّك المربّع لتختار الحتّة اللي بدك ياها.",
  "Drag the corners to cut the photo.": "اسحب الزوايا لتقصّ الصورة.",
  "Brush size": "حجم الريشة",
  "Text size": "حجم الكتابة",
  "Delete text": "امحي الكتابة",
  "Write something…": "اكتب شي…",
  Crop: "قصّ",
  Draw: "رسم",
  Text: "كتابة",
  Filters: "فلاتر",
  Original: "الأصلية",
  "B&W": "أبيض وأسود",
  Warm: "دافي",
  Vivid: "ألوان قوية",
  Soft: "ناعم",
};
